---
- hosts: client
  become: yes
  vars:
     system_user: ubuntu

  pre_tasks:

     - name : create www data
       user:
         name: www-data
         state: present

     - name: install docker-compose on targe
       get_url:
         url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
         dest: /usr/bin/docker-compose
         mode: 'u+x,g+x'
  roles:
    - role: ansible-role-containerized-wordpress

# important d'installer ansible-galaxy